### ISSUE TITLE
build scripts

### ISSUE THREAD

**Issue by AiyionPrime** [freifunkh/site#10]
It may be a nice feature to have build scripts for our build instances.
Like having only one shell file which gets executed by our jenkins-servers and does all the neccessary work.

**Comment by lemoer** [comment]
I would propose logging to the following path:
``` shell
logs/$(date --rfc-3339=seconds | tr " " "T")_${GLUON_TARGET}.log
```

**Comment by lemoer** [comment]
Maybe we could integrate #8

**Comment by lemoer** [comment]
We are now running the jenkins server for quite a while, while also providing nightly builds with it. Do you have any objections whether we should store the build procedure here?

My objections are:
- I often modify the build procedure to do some patching before the actual build, when I want to test something. This wouldn't be so easy anymore and would cause a lot of messy git commits.
- Updating the build procedure in general becomes more tedious. The scripts now pull the site repo, but if they are located in the site itself, then we have a chicken egg problem.

I would vote for closing with wontfix. Does anyone else have oppinions?

**Comment by AiyionPrime** [comment]
I hoped that by now we would've moved towards something like declarative pipelines; without pushing it.
Though I don't like having our builds running without jenkinsfiles like now,
I've got to admit it's doing good enough.
I'd not care about messy commits; we could store the repo in private if you cared.
But I'd not use Jenkinsfiles just to use Jenkinsfiles; but because they're superior to what we're doing now.
As long as they aren't, we shouldn't use them at all :/
Therefore vote for wontfix, for now.

**Comment by 1977er** [comment]
Maybe we can manually copy/paste the build scripts to a repo. I like the idea of having a well defined place to restore from after a crash.

**Comment by lemoer** [comment]
> I like the idea of having a well defined place to restore from after a crash.

Me aswell. Should we keep this issue open until this is done?

**Comment by CodeFetch** [comment]
Totally outdated. Jenkins works great now.
