### ISSUE TITLE
Consider use of gluon-web-mesh-vpn-fastd package

### ISSUE THREAD

**Issue by lemoer** [freifunkh/site#18]
> gluon-web module to enable and disable encryption for the mesh VPN

- This is only useful, if we also enable it also on gateway side
- Note that the package name was `gluon-luci-mesh-vpn-fastd` before lede.

**Comment by lemoer** [comment]
1. It's already enabled on gateway side.
2. This is an optional feature in expert mode, so I don't see any strong oppions in here.

I think, after testing we should announce it our release notes.

**Comment by lemoer** [comment]
Will be available in the next nightly builds.

**Comment by lemoer** [comment]
![screenshot from 2018-02-15 10-49-57](https://user-images.githubusercontent.com/601153/36250424-0c447276-123e-11e8-8205-5e833a3b03d3.png)

**Comment by 1977er** [comment]
Mal schauen, ob das wirklich "Geschwindigkeitsvorteile" bringt. Im aktuellen Netz tut es das eher nicht.

**Comment by lemoer** [comment]
Works. I'll close it.
