### ISSUE TITLE
n.ffh.zone should be reachable, when node is offline

### ISSUE THREAD

**Issue by lemoer** [freifunkh/site#22]

**Comment by lemoer** [comment]
Should work since we use a local resolver on the node.

**Comment by 1977er** [comment]
The server part should be okay, since we operate an open ntp service on a public IP address, but I'm not sure, whether the ntp client resolves FQDNs via this 54/udp hack.

Did you test that?

**Comment by 1977er** [comment]
Sorry, wrong topic. My mistake. :D
