### ISSUE TITLE
Disable 802.11b

### ISSUE THREAD

**Issue by lemoer** [freifunkh/site#25]
See: https://github.com/freifunk-darmstadt/site-ffda/blob/master/site.conf#L35-L37

Discussion here.

This should be included in release notes at least.

**Comment by Manawyrm** [comment]
Have had a good success with doing this in the past when using OpenWRT directly to cover a small fairground. Would recommend doing this.

**Comment by 1977er** [comment]
:thumbsup:

**Comment by lemoer** [comment]
Done.
