### ISSUE TITLE
Use dnscaching to provide nextnode addr

### ISSUE THREAD

**Issue by lemoer** [freifunkh/site#28]
https://gluon.readthedocs.io/en/v2017.1.x/features/dns-cache.html

This helps us to provide a convenient way to access the statuspage.

Document in the wiki afterwards: https://hannover.freifunk.net/wiki/Freifunk/RouterStatusseite

**Comment by 1977er** [comment]
Do we put all our recursive dns servers (all supernodes) into the dns.servers field? What about an anycast for next-supernode (fdca:ffee:8::8888)? ;-)

I would suggest "freifunkknoten" or "freifunk" as next_node.name as it sounds less technical.

**Comment by lemoer** [comment]
Done.
