### ISSUE TITLE
Wrong labels in domain selector

### ISSUE THREAD

**Issue by moridius** [freifunkh/site#30]
The domain selector in config mode doesn't show pretty labels yet.

![domain_selector](https://user-images.githubusercontent.com/9168718/39097586-8eac2962-465e-11e8-919a-4c32b76a0acb.jpg)

**Comment by lemoer** [comment]
Not sure yet, why this is a problem yet?

German proposal from @bschelm:
> "Hier kannst du deine Standortzugehörigkeit festlegen. Wähle deinen Stadtteil oder deine Stadt aus. Passt keine Auswahl, lass es einfach bei Default stehen. Die Standortzugehörigkeit legt fest, mit welchen Freifunk Knoten sich dein Knoten verbinden kann (Mesh-Netz)."

**Comment by lemoer** [comment]
TODO:
- [x] Es sollte keinen default geben.

**Comment by lemoer** [comment]
Should be fixed in next nightly.

**Comment by lemoer** [comment]
![screenshot from 2018-05-13 15-59-14](https://user-images.githubusercontent.com/601153/39968071-5c6002fc-56c7-11e8-9ed4-5889bf657598.png)
