### ISSUE TITLE
Legacy as Default domain in Config Mode?

### ISSUE THREAD

**Issue by Dark4MD** [freifunkh/site#35]
Legacy is still the default domain in the site.conf and also in the config mode. Shouldn't we change it to prevent new Users, that didn't chosse or forget to choose a domain in the dropdown, to set their domain to legacy?

**Comment by 1977er** [comment]
As far as I know the webform does not preselect anything on new installations. Did that change lately (with OpenWRT)?

**Comment by Dark4MD** [comment]
You are right, when i flashed the C7v5 with the vH12 Beta nothing was selected as you said. I will watch when this is happening again cause sometimes Legacy was already choosen, don't know why.

**Comment by 1977er** [comment]
Browser pre-filled forms?
