### ISSUE TITLE
vH23 does not include migration from older wireguard branches

### ISSUE THREAD

**Issue by lemoer** [freifunkh/site#68]
It seems like, vH23 is built without this commit: https://github.com/lemoer/gluon/commit/5f91e9fc0921b6d4a0bb74213427350fdbd40833

This is bad, because it will brick upgrades from vH21.*-wg-pr

**Comment by AiyionPrime** [comment]
Good call, thought about that commit yesterday on my way home :)

**Comment by AiyionPrime** [comment]
vH24 lies on the firmware server. Other than vH23 it contains cb02774 and ef8769f.
Updating from 21.xx while keeping the config is still a bad idea, due to missing upstream migration.

@lemoer feel free to close if you concur.

**Comment by lemoer** [comment]
Documented here: https://hannover.freifunk.net/wiki/Freifunk/FirmwareReleases#vH23
