### ISSUE TITLE
Test package gluon-radv-filterd

### ISSUE THREAD

**Issue by lemoer** [freifunkh/site#7]
Could be helpful, if we want to roll out public IPv6. This should avoid cross traffic. But I'm not sure, whether there are more things, why this package is helpful.

---

**Links:**
- Pull Request at gluon: https://github.com/freifunk-gluon/gluon/pull/838

----
**Description of the package:**
This package drops all incoming router advertisements except for the
default router with the best metric according to B.A.T.M.A.N. advanced.

Note that advertisements originating from the node itself (for example
via gluon-radvd) are not affected and considered at all.

[Read more...](https://github.com/freifunk-gluon/gluon/blob/6f2ad30c31bc9cea9f94cce4d1c017f6def208e6/package/gluon-radv-filterd/README.md)

---

**Comment by lemoer** [comment]
@1977er what's the state here?

**Comment by 1977er** [comment]
Pre-test done with simple RDNSS frames. Unfortunately the filter has no effect on rdnss frames. Looks like I have to test it with real router (prefix) annoucements.

**Comment by 1977er** [comment]
Works like a charm. Just tested at the wrong location last time. The Freifunk node itself can see all traffic of course. The filter only applies to the clients behind that node.

Recommendation for public use.

**Comment by lemoer** [comment]
nice!

**Comment by 1977er** [comment]
part of 0.14k
